spring:
  application:
    name: sigh

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sigh}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

server:
  port: ${SERVER_PORT:9090}

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

sigh:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh_expiration: ${JWT_REFRESH}
    issuer: ${JWT_ISSUER}